Update libraries for compatibility with CMake 4.0

diff --git a/deps/harfbuzz/.circleci/config.yml b/deps/harfbuzz/.circleci/config.yml
--- a/deps/harfbuzz/.circleci/config.yml
+++ b/deps/harfbuzz/.circleci/config.yml
@@ -3,121 +3,150 @@ version: 2.1
 executors:
   win32-executor:
     docker:
-      - image: cimg/base:edge-20.04
+      - image: ubuntu:24.04
   win64-executor:
     docker:
-      - image: cimg/base:edge-20.04
-  autotools-executor:
+      - image: ubuntu:24.04
+  dist-executor:
     docker:
-      - image: cimg/base:edge-20.04
+      - image: cimg/base:2023.10
 
 jobs:
 
   macos-aat-fonts:
     macos:
-      xcode: "12.5.1"
+      xcode: "15.3.0"
     steps:
       - checkout
-      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install pkg-config ragel freetype glib cairo python3 icu4c graphite2 gobject-introspection gtk-doc ninja
+      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install pkg-config ragel freetype glib cairo python3 icu4c graphite2 gobject-introspection ninja
       - run: pip3 install meson --upgrade
-      - run: PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig" meson build -Dcoretext=enabled -Dgraphite=enabled -Dauto_features=enabled -Dchafa=disabled
+      - run: brew link --force icu4c
+      - run: PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig" meson setup build -Dcoretext=enabled -Dgraphite=enabled -Dauto_features=enabled -Dchafa=disabled -Ddocs=disabled
       - run: meson compile -Cbuild
       - run: meson test -Cbuild --print-errorlogs
       - store_artifacts:
           path: build/meson-logs/
 
-  # will be dropped with autotools removal
-  distcheck:
-    executor: autotools-executor
+  dist:
+    executor: dist-executor
     steps:
       - checkout
-      - run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y git ninja-build binutils libtool autoconf automake make gcc g++ pkg-config ragel gtk-doc-tools gobject-introspection libfreetype6-dev libglib2.0-dev libgirepository1.0-dev libcairo2-dev libicu-dev libgraphite2-dev python3 python3-pip
+      - run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y git ninja-build binutils gcc g++ pkg-config ragel gtk-doc-tools gobject-introspection libfreetype6-dev libglib2.0-dev libgirepository1.0-dev libcairo2-dev libicu-dev libgraphite2-dev python3 python3-pip
       - run: pip3 install fonttools meson --upgrade
-      - run: ./autogen.sh
-      - run: make -j2 distcheck
-      - run: rm harfbuzz-* && make distdir
-      - run: cd harfbuzz-* && meson build && ninja -j2 -Cbuild test
-      - run: make dist
+      - run: meson setup build
+      - run: meson dist --no-tests -Cbuild
       - persist_to_workspace:
           root: .
-          paths: harfbuzz-*.tar.xz
+          paths: build/meson-dist/harfbuzz-*.tar.xz
 
   publish-dist:
-    executor: autotools-executor
+    executor: dist-executor
     steps:
       - checkout
       - attach_workspace:
           at: .
       - run: |
-          .ci/publish_release_artifact.sh harfbuzz-$CIRCLE_TAG.tar.xz
+          .ci/publish_release_artifact.sh build/meson-dist/harfbuzz-$CIRCLE_TAG.tar.xz
 
   fedora-valgrind:
     docker:
-      - image: fedora:33
+      - image: fedora:36
     steps:
       - checkout
       - run: dnf install -y pkg-config ragel valgrind gcc gcc-c++ meson git glib2-devel freetype-devel cairo-devel libicu-devel gobject-introspection-devel graphite2-devel redhat-rpm-config python python-pip || true
-      - run: meson build --buildtype=debugoptimized
-      - run: ninja -Cbuild -j9
-      # TOOD: increase timeouts and remove --no-suite=slow
-      - run: RUN_VALGRIND=1 meson test -Cbuild --no-suite=slow --wrap='valgrind --leak-check=full --error-exitcode=1' --print-errorlogs
-
-  alpine:
-    docker:
-      - image: alpine
-    steps:
-      - checkout
-      - run: apk update && apk add ragel gcc g++ glib-dev freetype-dev cairo-dev git py3-pip ninja
-      - run: pip3 install meson==0.52.0
-      - run: meson build --buildtype=minsize
-      - run: ninja -Cbuild -j9
-      - run: meson test -Cbuild --print-errorlogs
-
-  archlinux:
-    docker:
-      - image: archlinux/base
-    steps:
-      - checkout
-      - run: pacman --noconfirm -Syu freetype2 meson git clang cairo icu gettext gobject-introspection gcc gcc-libs glib2 graphite pkg-config ragel python python-pip base-devel gtk-doc
-      - run: pip install flake8 fonttools
-      - run: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
-      - run: meson build -Dgraphite=enabled -Dauto_features=enabled -Dexperimental_api=true
+      - run: meson setup build --buildtype=debugoptimized
       - run: meson compile -Cbuild -j9
-      - run: meson test -Cbuild --print-errorlogs
-      - run: meson dist -Cbuild
-      - run: clang -c src/harfbuzz.cc -DHB_NO_MT
-      - run: clang -c src/hb-*.cc -DHB_NO_MT -DHB_TINY -DHB_NO_OT_FONT
+      - run: RUN_VALGRIND=1 meson test -Cbuild -t 10 --no-suite=slow --wrap='valgrind --leak-check=full --error-exitcode=1' --print-errorlogs --num-processes=$(($(nproc)/2 + 1))
 
-  sanitizers:
+  minsize:
     docker:
-      - image: ubuntu:20.04
+      - image: ubuntu
+    steps:
+      - checkout
+      - run: apt update
+      - run: DEBIAN_FRONTEND=noninteractive apt install -y ninja-build binutils gcc g++ pkg-config ragel libfreetype6-dev libglib2.0-dev libcairo2-dev python3 python3-pip python3-venv
+      - run: |
+          python3 -m venv venv
+          source venv/bin/activate
+          pip3 install meson==0.56.0
+          meson setup build --buildtype=minsize
+          meson compile -Cbuild
+          meson test -Cbuild --print-errorlogs
+
+  asan-ubsan:
+    docker:
+      - image: ubuntu
     steps:
       - checkout
       - run: apt update || true
-      - run: DEBIAN_FRONTEND=noninteractive apt install -y clang lld git binutils meson pkg-config ragel libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev
-      # asan+ubsan
-      - run: rm -rf build && meson build --default-library=static -Db_sanitize=address,undefined --buildtype=debugoptimized --wrap-mode=nodownload -Dexperimental_api=true
-      - run: ninja -Cbuild -j8 && meson test -Cbuild --print-errorlogs | asan_symbolize | c++filt
-      # tsan
-      - run: rm -rf build && meson build --default-library=static -Db_sanitize=thread --buildtype=debugoptimized --wrap-mode=nodownload -Dexperimental_api=true
-      - run: ninja -Cbuild -j8 && meson test -Cbuild --print-errorlogs | asan_symbolize | c++filt
-      # msan, needs --force-fallback-for=glib,freetype2 also which doesn't work yet but runs fuzzer cases at least
-      - run: rm -rf build && meson build --default-library=static -Db_sanitize=memory --buildtype=debugoptimized --wrap-mode=nodownload -Dauto_features=disabled -Dtests=enabled -Dexperimental_api=true
-      - run: ninja -Cbuild -j8 && meson test -Cbuild --print-errorlogs | asan_symbolize | c++filt
-      - run: clang -c src/harfbuzz.cc src/hb-subset*.cc -DHB_NO_MT -Werror -std=c++2a
+      - run: DEBIAN_FRONTEND=noninteractive apt install -y python3 python3-pip python3-venv ninja-build clang lld git binutils pkg-config ragel libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev
+      - run: |
+          python3 -m venv venv
+          source venv/bin/activate
+          pip3 install meson==0.56.0
+          CC=clang CXX=clang++ meson setup build --default-library=static -Db_sanitize=address,undefined --buildtype=debugoptimized --wrap-mode=nodownload -Dexperimental_api=true
+          meson compile -Cbuild -j9
+          meson test -Cbuild -t 10 --print-errorlogs | asan_symbolize | c++filt
+
+  tsan:
+    docker:
+      - image: ubuntu:24.04
+    steps:
+      - checkout
+      - run: apt update || true
+      - run: DEBIAN_FRONTEND=noninteractive apt install -y python3 python3-pip python3-venv ninja-build clang lld git binutils pkg-config ragel libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev
+      - run: |
+          python3 -m venv venv
+          source venv/bin/activate
+          pip3 install meson==0.56.0
+          CC=clang CXX=clang++ meson setup build --default-library=static -Db_sanitize=thread --buildtype=debugoptimized --wrap-mode=nodownload -Dexperimental_api=true
+          meson compile -Cbuild -j9
+          meson test -Cbuild -t 10 --print-errorlogs | asan_symbolize | c++filt
+
+  msan:
+    docker:
+      - image: ubuntu:24.04
+    steps:
+      - checkout
+      - run: apt update || true
+      - run: DEBIAN_FRONTEND=noninteractive apt install -y python3 python3-pip python3-venv ninja-build clang lld git binutils pkg-config ragel libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev
+      - run: |
+          python3 -m venv venv
+          source venv/bin/activate
+          pip3 install meson==0.56.0
+          # msan, needs --force-fallback-for=glib,freetype2 also which doesn't work yet but runs fuzzer cases at least
+          CC=clang CXX=clang++ meson setup build --default-library=static -Db_sanitize=memory --buildtype=debugoptimized --wrap-mode=nodownload -Dauto_features=disabled -Dtests=enabled -Dexperimental_api=true
+          meson compile -Cbuild -j9
+          meson test -Cbuild -t 10 --print-errorlogs | asan_symbolize | c++filt
+
+  clang-cxx2a:
+    docker:
+      - image: ubuntu
+    steps:
+      - checkout
+      - run: apt update || true
+      - run: DEBIAN_FRONTEND=noninteractive apt install -y clang lld git binutils
+      - run: clang -c src/harfbuzz-subset.cc -DHB_NO_MT -Werror -std=c++2a
 
   crossbuild-win32:
     executor: win32-executor
     steps:
       - checkout
-      - run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y ninja-build gtk-doc-tools python3 python3-pip git g++-mingw-w64-i686 zip
-      - run: pip3 install meson==0.56.0 --upgrade
-      - run: .ci/build-win32.sh
+      - run: dpkg --add-architecture i386
+      - run: apt update
+      - run: DEBIAN_FRONTEND=noninteractive apt install -y ninja-build python3 python3-pip python3-venv git g++-mingw-w64-i686 zip wine wine32
+      - run: |
+          export LANG=en_US.UTF-8
+          python3 -m venv venv
+          source venv/bin/activate
+          pip3 install meson==1.6.0
+          bash .ci/build-win.sh 32
+          meson devenv -Cbuild-win32 meson test --print-errorlogs --suite=harfbuzz
       - store_artifacts:
           path: harfbuzz-win32.zip
       - persist_to_workspace:
           root: .
-          paths: harfbuzz-win32.zip
+          paths: [harfbuzz-win32.zip]
 
   publish-win32:
     executor: win32-executor
@@ -133,14 +162,20 @@ jobs:
     executor: win64-executor
     steps:
       - checkout
-      - run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y ninja-build gtk-doc-tools python3 python3-pip git g++-mingw-w64-x86-64 zip
-      - run: pip3 install meson==0.56.0 --upgrade
-      - run: bash .ci/build-win64.sh
+      - run: apt update
+      - run: DEBIAN_FRONTEND=noninteractive apt install -y ninja-build python3 python3-pip python3-venv git g++-mingw-w64-x86-64 zip wine wine64
+      - run: |
+          export LANG=en_US.UTF-8
+          python3 -m venv venv
+          source venv/bin/activate
+          pip3 install meson==1.6.0
+          bash .ci/build-win.sh 64
+          meson devenv -Cbuild-win64 meson test --print-errorlogs --suite=harfbuzz
       - store_artifacts:
           path: harfbuzz-win64.zip
       - persist_to_workspace:
           root: .
-          paths: harfbuzz-win64.zip
+          paths: [harfbuzz-win64.zip]
 
   publish-win64:
     executor: win64-executor
@@ -159,22 +194,24 @@ workflows:
   build:
     jobs:
       - macos-aat-fonts
-      - distcheck:
+      - dist:
           filters: # must have filter or won't work as a dependency
             tags:
               only: /.*/
       - publish-dist:
           requires:
-            - distcheck
+            - dist
           filters:
             tags:
               only: /^\d+\.\d+\.\d+$/
             branches:
               ignore: /.*/
       - fedora-valgrind
-      - alpine
-     #- archlinux
-      - sanitizers
+      - minsize
+      - asan-ubsan
+      - tsan
+      - msan
+      - clang-cxx2a
       - crossbuild-win32:
           filters: # must have filter or won't work as a dependency
             tags:
